name: kk_demo
description: ''
version: '0.8'
author: kyakkala@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: kk_demo
  parentArtefactID: kyakkalaprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-05-11 09:10:37'
  modifiedAt: '2023-05-11 09:10:37'
pipelines:
  pipelines/standard_pipeline:
    name: standard_pipeline
    description: ''
    author: kyakkala@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-14 04:25:42'
    modifiedAt: '2023-05-14 06:15:06'
    datasets:
      inputs:
      - datasets/customer_ds
      - datasets/orders_ds
      outputs:
      - datasets/customer_revenue
    subgraphs:
    - subgraphs/revenue_enrich
    dependencies: {}
datasets:
  datasets/customer_ds:
    name: raw_customer_ds
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:15:28'
    modifiedAt: '2023-05-17 08:16:14'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:15:28'
        modifiedAt: '2023-05-13 12:15:28'
  datasets/orders_ds:
    name: raw_orders_ds
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:16:05'
    modifiedAt: '2023-05-17 08:16:30'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:16:05'
        modifiedAt: '2023-05-13 12:16:05'
  datasets/customer_revenue:
    name: customer_rpt
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:25:44'
    modifiedAt: '2023-05-17 08:19:53'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:25:44'
        modifiedAt: '2023-05-13 12:25:44'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-05-11 09:10:37'
  modifiedAt: '2023-05-14 06:14:32'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/revenue_enrich:
    name: revenue_enrich
    description: ''
    author: kyakkala@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-05-13 12:24:43'
    modifiedAt: '2023-05-14 06:14:03'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
