name: kk_demo
description: ''
version: '0.9'
author: kyakkala@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: kk_demo
  parentArtefactID: kyakkalaprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-05-11 09:10:37'
pipelines:
  pipelines/standard_pipeline:
    name: standard_pipeline
    description: ''
    author: kyakkala@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-14 04:25:42'
    datasets:
      inputs:
      - datasets/customer_ds
      - datasets/orders_ds
      outputs:
      - datasets/customer_revenue
    subgraphs:
    - subgraphs/revenue_enrich
    dependencies: {}
  pipelines/customer_orders_catalog:
    name: customer_orders_catalog
    description: ''
    author: kyakkala@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-26 08:20:07'
    datasets:
      inputs:
      - datasets/customer_delta
      - datasets/customer_ds
      - datasets/nested_json
      - datasets/orders_delta
      - datasets/orders_ds
      outputs:
      - datasets/customer_delta
      - datasets/customer_orders_catalog
      - datasets/orders_delta
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_ds:
    name: raw_customer_ds
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:15:28'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:15:28'
  datasets/orders_ds:
    name: raw_orders_ds
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:16:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:16:05'
  datasets/customer_revenue:
    name: customer_rpt
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:25:44'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:25:44'
  datasets/customer_delta:
    name: customer_delta
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-10-26 08:22:03'
    mode: batch
    physicalDatasets:
      kk_fab:
        fabricId: 5544
        datasetType: Database
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-10-26 08:22:03'
  datasets/orders_delta:
    name: orders_delta
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-10-26 08:23:35'
    mode: batch
    physicalDatasets:
      kk_fab:
        fabricId: 5544
        datasetType: Database
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-10-26 08:23:35'
  datasets/customer_orders_catalog:
    name: customer_orders_delta
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-10-26 08:25:25'
    mode: batch
    physicalDatasets:
      kk_fab:
        fabricId: 5544
        datasetType: Database
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-10-26 08:25:25'
  datasets/nested_json:
    name: customer_nested_json
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-10-26 08:48:55'
    mode: batch
    physicalDatasets:
      kk_fab:
        fabricId: 5544
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-10-26 08:48:55'
templates: {}
jobs:
  jobs/revenue_monthly:
    name: revenue_monthly
    description: ''
    fabricUID: 647
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: Small
    scheduleCron: 0 0 0 1 * ? *
    timeout: null
    alerting:
      emails: kyakkala@prophecy.io
      onStart: false
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/standard_pipeline
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2023-05-17 10:19:12'
    author: kyakkala@prophecy.io
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
functions:
  author: null
  createdAt: '2023-05-11 09:10:37'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/revenue_enrich:
    name: revenue_enrich
    description: ''
    author: kyakkala@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-05-13 12:24:43'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2023-10-26 08:18:34'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-26 08:18:34'
pipelineConfigurations: {}
