name: kk_demo
description: ''
version: '0.4'
author: kyakkala@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: kk_demo
  parentArtefactID: kyakkalaprophecy.io_team
  buildSystem: wheel
  author: null
  createdAt: '2023-05-11 09:10:37'
  modifiedAt: '2023-05-11 09:10:37'
pipelines:
  pipelines/standard_pipeline:
    name: standard_pipeline
    description: ''
    author: kyakkala@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-14 04:25:42'
    modifiedAt: '2023-05-14 05:18:04'
    datasets:
      inputs:
      - datasets/customer_ds
      - datasets/orders_ds
      outputs:
      - datasets/customer_revenue
    subgraphs:
    - subgraphs/revenue_enrich
    dependencies: {}
datasets:
  datasets/customer_ds:
    name: ds1
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:15:28'
    modifiedAt: '2023-05-14 04:23:27'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:15:28'
        modifiedAt: '2023-05-13 12:15:28'
  datasets/orders_ds:
    name: ds2
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:16:05'
    modifiedAt: '2023-05-14 04:23:15'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:16:05'
        modifiedAt: '2023-05-13 12:16:05'
  datasets/customer_revenue:
    name: co_report
    description: ''
    author: kyakkala@prophecy.io
    createdAt: '2023-05-13 12:25:44'
    modifiedAt: '2023-05-14 05:10:31'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 1
        datasetType: File
        description: ''
        author: kyakkala@prophecy.io
        createdAt: '2023-05-13 12:25:44'
        modifiedAt: '2023-05-13 12:25:44'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-05-11 09:10:37'
  modifiedAt: '2023-05-14 05:18:04'
  gems: {}
  udfs:
    udfs/kk_square:
      name: kk_square
      description: ''
      tags: []
      inputs: []
      outputs: []
      author: kyakkala@prophecy.io
      createdAt: '2022-12-15 18:04:50'
      modifiedAt: '2022-12-15 18:04:50'
  udafs: {}
  expressions: {}
subgraphs:
  subgraphs/revenue_enrich:
    name: revenue_enrich
    description: ''
    author: kyakkala@prophecy.io
    language: python
    artefactID: ''
    mode: batch
    createdAt: '2023-05-13 12:24:43'
    modifiedAt: '2023-05-14 05:18:04'
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: []
projectDependencies: {}
pipelineConfigurations: {}
